name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix-channel: ["nixos-unstable", "nixos-21.05"]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:${{ matrix.nix-channel }}
    - uses: cachix/cachix-action@v10
      with:
        name: blitz
    - run: nix-shell --run "echo OK"
